# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jedec"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["sen"]
  s.date = "2012-04-15"
  s.description = "Ruby/Jedec is a Ruby library that provides a class to read and write JEDEC fuse data files, used for programmable logic devices."
  s.email = "ruby-jedec@sen.cx"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README"
  ]
  s.homepage = "http://github.com/sarahemm/ruby-jedec"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Library for dealing with JEDEC fuse files."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

